"""add two cloumns

Revision ID: 139d326004c2
Revises: 2416fb68207f
Create Date: 2025-12-03 23:24:31.836421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '139d326004c2'
down_revision = '2416fb68207f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return', sa.DateTime(), nullable=True))
        batch_op.drop_column('expected_return_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('expected_return')

    # ### end Alembic commands ###
