"""Add Faculty/Staff and assignment fks

Revision ID: 2005147651cb
Revises: 68137eafcd28
Create Date: 2025-11-24 19:39:09.890994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2005147651cb'
down_revision = '68137eafcd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('doj', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_faculty_faculty_id'), ['faculty_id'], unique=True)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('doj', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_staff_id'), ['staff_id'], unique=True)

    op.create_table('staff_lab_incharge',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('room_lab_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_lab_id'], ['room_lab.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id', 'room_lab_id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_faculty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_staff_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipment_assigned_to_faculty_id'), ['assigned_to_faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_assigned_to_staff_id'), ['assigned_to_staff_id'], unique=False)
        batch_op.create_foreign_key('fk_equipment_assigned_to_faculty_id', 'faculty', ['assigned_to_faculty_id'], ['id'])
        batch_op.create_foreign_key('fk_equipment_assigned_to_staff_id', 'staff', ['assigned_to_staff_id'], ['id'])

    with op.batch_alter_table('equipment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_faculty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_staff_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_equipment_history_assigned_to_faculty_id'), ['assigned_to_faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_history_assigned_to_staff_id'), ['assigned_to_staff_id'], unique=False)

    with op.batch_alter_table('workstation_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.alter_column('student_roll',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_workstation_assignment_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workstation_assignment_staff_id'), ['staff_id'], unique=False)
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_workstation_assignment_staff_id'))
        batch_op.drop_index(batch_op.f('ix_workstation_assignment_faculty_id'))
        batch_op.alter_column('student_roll',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('staff_id')
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('equipment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_history_assigned_to_staff_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_history_assigned_to_faculty_id'))
        batch_op.drop_column('assigned_to_staff_id')
        batch_op.drop_column('assigned_to_faculty_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_assigned_to_staff_id', type_='foreignkey')
        batch_op.drop_constraint('fk_equipment_assigned_to_faculty_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_equipment_assigned_to_staff_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_assigned_to_faculty_id'))
        batch_op.drop_column('assigned_to_staff_id')
        batch_op.drop_column('assigned_to_faculty_id')

    op.drop_table('staff_lab_incharge')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_email'))

    op.drop_table('staff')
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_email'))

    op.drop_table('faculty')
    # ### end Alembic commands ###
