"""add two cloumns

Revision ID: 2416fb68207f
Revises: 52fd600d6f55
Create Date: 2025-12-03 23:02:13.352205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2416fb68207f'
down_revision = '52fd600d6f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('equipment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_history', schema=None) as batch_op:
        batch_op.drop_column('expected_return')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('expected_return_date')

    # ### end Alembic commands ###
