"""Add ram GB column

Revision ID: 26689d980be8
Revises: 4fb0466b934b
Create Date: 2025-12-05 12:03:04.633088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26689d980be8'
down_revision = '4fb0466b934b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ram_size_gb', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.drop_column('ram_size_gb')

    # ### end Alembic commands ###
