"""Added vendor, warranty, PO fields to Equipment and WorkstationAsset

Revision ID: 37357289ca06
Revises: 3c9f02f0b654
Create Date: 2025-10-21 14:48:57.879302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37357289ca06'
down_revision = '3c9f02f0b654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('warranty_start', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vendor_company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('vendor_contact_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vendor_mobile', sa.String(length=20), nullable=True))
        batch_op.drop_column('purchase_date')

    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('warranty_start', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('warranty_expiry', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vendor_company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('vendor_contact_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vendor_mobile', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.drop_column('vendor_mobile')
        batch_op.drop_column('vendor_contact_person')
        batch_op.drop_column('vendor_company')
        batch_op.drop_column('warranty_expiry')
        batch_op.drop_column('warranty_start')
        batch_op.drop_column('po_number')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('vendor_mobile')
        batch_op.drop_column('vendor_contact_person')
        batch_op.drop_column('vendor_company')
        batch_op.drop_column('warranty_start')
        batch_op.drop_column('po_number')

    # ### end Alembic commands ###
