"""Add user_id foreign key to Student

Revision ID: 3c72ecdf2950
Revises: 17e7301a36e1
Create Date: 2025-09-13 21:51:47.017625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c72ecdf2950'
down_revision = '17e7301a36e1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('student', schema=None) as batch_op:
        # Step 1: add user_id column as nullable for now
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

        # Step 2: add foreign key with explicit name
        batch_op.create_foreign_key(
            'fk_student_user',    # constraint name
            'user',               # referred table
            ['user_id'],          # local col
            ['id']                # remote col
        )

        # Step 3: add unique constraint on email with explicit name
        batch_op.create_unique_constraint(
            'uq_student_email',
            ['email']
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
