"""Add department_code to WorkstationAsset

Revision ID: 4820c21cfb55
Revises: 3c72ecdf2950
Create Date: 2025-09-15 19:51:48.080313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4820c21cfb55'
down_revision = '3c72ecdf2950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_code', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_workstation_asset_department_code'), ['department_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workstation_asset_department_code'))
        batch_op.drop_column('department_code')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
