"""add assigned_by to WorkstationAssignment

Revision ID: 52fd600d6f55
Revises: 2005147651cb
Create Date: 2025-12-03 22:24:42.098810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fd600d6f55'
down_revision = '2005147651cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_assignment', schema=None) as batch_op:
        batch_op.drop_column('assigned_by')

    # ### end Alembic commands ###
