"""initial schema

Revision ID: 6288dec7d77f
Revises: 
Create Date: 2025-08-15 22:11:15.037468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6288dec7d77f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provisioning_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=32), nullable=False),
    sa.Column('os_image', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provisioning_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provisioning_request_mac_address'), ['mac_address'], unique=False)

    op.create_table('room_lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('staff_incharge', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_lab', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_lab_name'), ['name'], unique=True)

    op.create_table('student',
    sa.Column('roll', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=20), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('joining_year', sa.String(length=10), nullable=True),
    sa.Column('faculty', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('roll')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('workstation_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('otherManufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('otherOs', sa.String(length=50), nullable=True),
    sa.Column('processor', sa.String(length=100), nullable=True),
    sa.Column('cores', sa.String(length=10), nullable=True),
    sa.Column('ram', sa.String(length=20), nullable=True),
    sa.Column('otherRam', sa.String(length=20), nullable=True),
    sa.Column('storage_type1', sa.String(length=50), nullable=True),
    sa.Column('storage_capacity1', sa.String(length=20), nullable=True),
    sa.Column('storage_type2', sa.String(length=50), nullable=True),
    sa.Column('storage_capacity2', sa.String(length=20), nullable=True),
    sa.Column('gpu', sa.String(length=100), nullable=True),
    sa.Column('vram', sa.String(length=10), nullable=True),
    sa.Column('keyboard_provided', sa.String(length=10), nullable=True),
    sa.Column('keyboard_details', sa.String(length=100), nullable=True),
    sa.Column('mouse_provided', sa.String(length=10), nullable=True),
    sa.Column('mouse_details', sa.String(length=100), nullable=True),
    sa.Column('monitor_provided', sa.String(length=20), nullable=True),
    sa.Column('monitor_details', sa.String(length=100), nullable=True),
    sa.Column('monitor_size', sa.String(length=10), nullable=True),
    sa.Column('monitor_serial', sa.String(length=100), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('po_date', sa.String(length=20), nullable=True),
    sa.Column('source_of_fund', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workstation_asset_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_workstation_asset_status'), ['status'], unique=False)

    op.create_table('cubicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('room_lab_id', sa.Integer(), nullable=False),
    sa.Column('student_roll', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['room_lab_id'], ['room_lab.id'], ),
    sa.ForeignKeyConstraint(['student_roll'], ['student.roll'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cubicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cubicle_student_roll'), ['student_roll'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.String(length=20), nullable=True),
    sa.Column('purchase_date', sa.String(length=20), nullable=True),
    sa.Column('warranty_expiry', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('intender_name', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('department_code', sa.String(length=100), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('assigned_to_roll', sa.String(length=20), nullable=True),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_roll'], ['student.roll'], name='fk_equipment_assigned_to_roll'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_assigned_to_roll'), ['assigned_to_roll'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_serial_number'), ['serial_number'], unique=True)

    op.create_table('equipment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_roll', sa.String(length=20), nullable=True),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('unassigned_date', sa.DateTime(), nullable=True),
    sa.Column('status_snapshot', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_roll'], ['student.roll'], name='fk_equipment_history_assigned_to_roll'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_history_assigned_to_roll'), ['assigned_to_roll'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_history_equipment_id'), ['equipment_id'], unique=False)

    op.create_table('workstation_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workstation_id', sa.Integer(), nullable=False),
    sa.Column('student_roll', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.String(length=20), nullable=False),
    sa.Column('system_required_till', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_roll'], ['student.roll'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstation_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workstation_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workstation_assignment_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_workstation_assignment_student_roll'), ['student_roll'], unique=False)
        batch_op.create_index(batch_op.f('ix_workstation_assignment_workstation_id'), ['workstation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workstation_assignment_workstation_id'))
        batch_op.drop_index(batch_op.f('ix_workstation_assignment_student_roll'))
        batch_op.drop_index(batch_op.f('ix_workstation_assignment_is_active'))

    op.drop_table('workstation_assignment')
    with op.batch_alter_table('equipment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_history_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_history_assigned_to_roll'))

    op.drop_table('equipment_history')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_serial_number'))
        batch_op.drop_index(batch_op.f('ix_equipment_assigned_to_roll'))

    op.drop_table('equipment')
    with op.batch_alter_table('cubicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cubicle_student_roll'))

    op.drop_table('cubicle')
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workstation_asset_status'))
        batch_op.drop_index(batch_op.f('ix_workstation_asset_serial'))

    op.drop_table('workstation_asset')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('student')
    with op.batch_alter_table('room_lab', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_lab_name'))

    op.drop_table('room_lab')
    with op.batch_alter_table('provisioning_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provisioning_request_mac_address'))

    op.drop_table('provisioning_request')
    # ### end Alembic commands ###
