"""Rebuild migrations including profile_photo

Revision ID: 68137eafcd28
Revises: 
Create Date: 2025-11-03 19:32:14.235351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68137eafcd28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('warranty_start', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vendor_company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('vendor_contact_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vendor_mobile', sa.String(length=20), nullable=True))
        batch_op.drop_column('purchase_date')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=200), nullable=True))
        batch_op.drop_constraint(batch_op.f('student_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('warranty_start', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('warranty_expiry', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vendor_company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('vendor_contact_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vendor_mobile', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.drop_column('vendor_mobile')
        batch_op.drop_column('vendor_contact_person')
        batch_op.drop_column('vendor_company')
        batch_op.drop_column('warranty_expiry')
        batch_op.drop_column('warranty_start')
        batch_op.drop_column('po_number')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('profile_photo')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('vendor_mobile')
        batch_op.drop_column('vendor_contact_person')
        batch_op.drop_column('vendor_company')
        batch_op.drop_column('warranty_start')
        batch_op.drop_column('po_number')

    # ### end Alembic commands ###
