"""Fix SlurmAccount FK to Student.roll

Revision ID: 714d8ff1fa8a
Revises: 8313acd3fe09
Create Date: 2025-09-01 21:50:48.988157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714d8ff1fa8a'
down_revision = '8313acd3fe09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slurm_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['roll'], ['student.roll'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slurm_account')
    # ### end Alembic commands ###
