"""Add location and indenter to WorkstationAsset

Revision ID: 8313acd3fe09
Revises: 6288dec7d77f
Create Date: 2025-08-16 20:52:59.970031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8313acd3fe09'
down_revision = '6288dec7d77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('indenter', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_asset', schema=None) as batch_op:
        batch_op.drop_column('indenter')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
