"""Added complete schema with MAC and cubicle seeding

Revision ID: 8e2aee9403ac
Revises: 31d4073638ac
Create Date: 2025-08-06 13:05:42.663616
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8e2aee9403ac'
down_revision = '31d4073638ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        # Skip dropping to avoid "No such constraint" error
        # batch_op.drop_constraint('fk_equipment_assigned_to_roll', type_='foreignkey')
        batch_op.create_foreign_key('fk_equipment_assigned_to_roll', 'student', ['assigned_to_roll'], ['roll'])

    with op.batch_alter_table('equipment_history', schema=None) as batch_op:
        # Currently no FK constraints dropped here
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'])

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_assigned_to_roll', type_='foreignkey')
        batch_op.create_foreign_key('fk_equipment_assigned_to_roll', 'workstation', ['assigned_to_roll'], ['roll'])
    # ### end Alembic commands ###

