"""Add processors/gpus JSON, typed fields, po_invoice_filename, status

Revision ID: 948c09433098
Revises: e3fbcccbe2c4
Create Date: 2025-12-04 16:57:56.568669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948c09433098'
down_revision = 'e3fbcccbe2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_assignment', schema=None) as batch_op:
        batch_op.alter_column('issue_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('system_required_till',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_constraint('workstation_assignment_workstation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'workstation_asset', ['workstation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workstation_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('workstation_assignment_workstation_id_fkey', 'workstation_asset', ['workstation_id'], ['id'])
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('system_required_till',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('issue_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
