"""Add asset_status_log

Revision ID: c7b50c120039
Revises: 26689d980be8
Create Date: 2025-12-05 20:39:49.074999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b50c120039'
down_revision = '26689d980be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.String(length=120), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['workstation_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_status_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_status_log_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_status_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_status_log_asset_id'))

    op.drop_table('asset_status_log')
    # ### end Alembic commands ###
